// Print-friendly sąskaita-faktūra. Designed so Cmd+P (or the "Print"
// button above) produces a valid LT/EU invoice PDF without any
// external dependency.

import type { InvoiceDetail } from "@/services/invoices";

export function InvoicePrintView({ detail }: { detail: InvoiceDetail }) {
  const { invoice, items, issuer } = detail;
  const dateStr = (iso: string | null) =>
    iso ? new Date(iso).toLocaleDateString("en-GB") : "—";

  return (
    <article className="bg-white rounded-2xl shadow-soft p-8 max-w-3xl mx-auto print:shadow-none print:rounded-none print:p-0">
      {/* Header */}
      <header className="flex items-start justify-between gap-6 mb-8 pb-5 border-b border-ink-200">
        <div>
          <p className="text-[11px] uppercase tracking-[0.18em] text-ink-500 font-semibold">Sąskaita-faktūra</p>
          <h1 className="text-2xl font-semibold mt-1 text-ink-900">{invoice.number}</h1>
          <p className="text-[12px] text-ink-500 mt-1">
            Issued {dateStr(invoice.issued_at)}
            {invoice.due_at && <> · Due {dateStr(invoice.due_at)}</>}
          </p>
        </div>
        <div className="text-right">
          <StatusBadge status={invoice.status} />
        </div>
      </header>

      {/* Issuer / recipient */}
      <section className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8 text-[13px]">
        <div>
          <p className="text-[11px] uppercase tracking-[0.12em] text-ink-500 font-semibold mb-1">From</p>
          <p className="font-semibold text-ink-900">{issuer.legal_name ?? "—"}</p>
          {issuer.business_code  && <p className="text-ink-700">Code: {issuer.business_code}</p>}
          {issuer.vat_code       && <p className="text-ink-700">VAT: {issuer.vat_code}</p>}
          {issuer.business_address && <p className="text-ink-700 mt-1 whitespace-pre-wrap">{issuer.business_address}</p>}
          {issuer.iban           && <p className="text-ink-700 mt-1">IBAN: {issuer.iban}</p>}
        </div>
        <div>
          <p className="text-[11px] uppercase tracking-[0.12em] text-ink-500 font-semibold mb-1">To</p>
          <p className="font-semibold text-ink-900">{invoice.client?.full_name ?? "—"}</p>
          {invoice.client?.email && <p className="text-ink-700">{invoice.client.email}</p>}
          {invoice.client?.phone && <p className="text-ink-700">{invoice.client.phone}</p>}
        </div>
      </section>

      {/* Items */}
      <section className="mb-8">
        <table className="w-full text-[13px]">
          <thead>
            <tr className="text-[10px] uppercase tracking-[0.12em] text-ink-500 font-semibold">
              <th className="text-left  py-2 border-b border-ink-200">Description</th>
              <th className="text-right py-2 border-b border-ink-200">Qty</th>
              <th className="text-right py-2 border-b border-ink-200">Unit price</th>
              <th className="text-right py-2 border-b border-ink-200">Total</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-ink-100">
            {items.map((it) => (
              <tr key={it.id}>
                <td className="py-2.5 text-ink-900">{it.description}</td>
                <td className="py-2.5 text-right tabular-nums text-ink-700">{Number(it.quantity)}</td>
                <td className="py-2.5 text-right tabular-nums text-ink-700">€{Number(it.unit_price).toFixed(2)}</td>
                <td className="py-2.5 text-right tabular-nums font-semibold text-ink-900">€{Number(it.line_total).toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      {/* Totals */}
      <section className="flex justify-end mb-8">
        <table className="text-[13px] min-w-[260px]">
          <tbody>
            <tr><td className="py-1.5 text-ink-500">Subtotal</td>
                <td className="py-1.5 text-right tabular-nums">€{Number(invoice.subtotal).toFixed(2)}</td></tr>
            {Number(invoice.vat_rate) > 0 && (
              <tr><td className="py-1.5 text-ink-500">VAT {invoice.vat_rate}%</td>
                  <td className="py-1.5 text-right tabular-nums">€{Number(invoice.vat_amount).toFixed(2)}</td></tr>
            )}
            <tr className="border-t border-ink-200">
              <td className="py-2 text-ink-900 font-semibold">Total</td>
              <td className="py-2 text-right tabular-nums text-xl font-semibold text-ink-900">€{Number(invoice.total).toFixed(2)}</td>
            </tr>
          </tbody>
        </table>
      </section>

      {invoice.notes && (
        <section className="mb-6">
          <p className="text-[11px] uppercase tracking-[0.12em] text-ink-500 font-semibold mb-1">Notes</p>
          <p className="text-[13px] text-ink-700 whitespace-pre-wrap">{invoice.notes}</p>
        </section>
      )}

      <footer className="border-t border-ink-200 pt-4 mt-6 text-[11px] text-ink-500">
        Generated by Longrein · longrein.eu
      </footer>
    </article>
  );
}

function StatusBadge({ status }: { status: "issued" | "paid" | "overdue" | "cancelled" }) {
  const map: Record<string, string> = {
    issued:    "bg-amber-50 text-amber-800",
    paid:      "bg-emerald-50 text-emerald-700",
    overdue:   "bg-rose-50 text-rose-700",
    cancelled: "bg-ink-100 text-ink-600",
  };
  return (
    <span className={`text-[11px] px-2.5 py-1 rounded-full font-medium ${map[status] ?? ""}`}>
      {status}
    </span>
  );
}
